<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Filmes.Application\Filmes.Application.csproj" />
    <ProjectReference Include="..\Filmes.Infraestruture\Filmes.Infraestruture.csproj" />
  </ItemGroup>

</Project>
